### PR TITLE
Pull Request as discussed

### PR DESCRIPTION
**Pull request by jonofe**

### CODE REVIEW

**Comment by jonofe** [comment]
Changed the line delimiter to \n for all files and sent a pull request.

**Comment by sqmk** [comment]
PHP tests look great. Coding standards will need to be addressed.

Just like running tests, you can run `./vendor/bin/phpcs --standard=tests/phpcs.xml library/` from phue root directory to test coding standards. If that and phpunit tests passed, travis should pass as well.

The README still also needs to be updated to what it was. You can change the broken gitdoc api URL and fix code examples with PHP 5.3 syntax, but everything else should remain if possible.

**Comment by jonofe** [comment]
I installed phpcs via pear. I neither have phpcs in ./vendor/bin nor 
phpcs.xml in tests.
What did I wrong?

------ Originalnachricht ------
Von: "Michael Squires" <notifications@github.com>
An: "sqmk/Phue" <Phue@noreply.github.com>
Cc: "jonofe" <andre.feld@anrath.net>
Gesendet: 23.03.2016 23:48:44
Betreff: Re: [Phue] Pull Request as discussed (#105)

**Comment by sqmk** [comment]
If you are on an outdated version of composer, can you try `composer install --dev`? code_sniffer is definitely included as a dependency, and running locally for me.

**Comment by sqmk** [comment]
Excellent. I'll be tagging this as v1.4.0, and creating a release branch release/1.x for all PHP 5.3+ changes, bug fixes going forward.

**Comment by sqmk** [comment]
Oops, the only thing left is fixes to README. This should be corrected to mostly what sqmk/Phue current README contains, with the your code sample changes and other minor fixes. After that, I can merge this in!

**Comment by jonofe** [comment]
just updated the README.md and all checks are now running without 
errors.
so, good to go ... :)

Do I have add a new pull request?

------ Originalnachricht ------
Von: "Michael Squires" <notifications@github.com>
An: "sqmk/Phue" <Phue@noreply.github.com>
Cc: "jonofe" <andre.feld@anrath.net>
Gesendet: 24.03.2016 00:16:45
Betreff: Re: [Phue] Pull Request as discussed (#105)

**Comment by sqmk** [comment]
No need for a new PR. Your PR will pick up any new changes you commit automatically!

Things look good here. Merging now.

**Comment by jonofe** [comment]
perfect. thanks for your patience with github newbie...
and sorry again for the "Interesting" start ;-)

------ Originalnachricht ------
Von: "Michael Squires" <notifications@github.com>
An: "sqmk/Phue" <Phue@noreply.github.com>
Cc: "jonofe" <andre.feld@anrath.net>
Gesendet: 24.03.2016 00:22:40
Betreff: Re: [Phue] Pull Request as discussed (#105)

**Comment by sqmk** [comment]
No worries. Good going on the changes and PR, and handling the tests and coding standards fixes!

**Comment by jonofe** [comment]
Just dropped packagist and github fork ...
Wish u a nice remaining day ... need sleep now, it's 01:00 am in Germany 
:)

------ Originalnachricht ------
Von: "Michael Squires" <notifications@github.com>
An: "sqmk/Phue" <Phue@noreply.github.com>
Cc: "jonofe" <andre.feld@anrath.net>
Gesendet: 24.03.2016 00:52:27
Betreff: Re: [Phue] Pull Request as discussed (#105)

**Comment by jonofe** [comment]
Hi Michael,

after using the Phue class during the last two days, I found out, that 
there is a difference in behaviour among php 5.3 and php 5.6.
When I call the function getColorTemp() for HUE devices other than 
Bulbs, there is not ColorTemp 'ct' attribute in the light data 
structure.
On PHP 5.3 that results in an error "Light.php line: 369 | Undefined 
property: stdClass::$ct" while in php 5.6 (Phue 1.3.0) there's no output 
at all.
Do you know why this could happen?


Additionally there might be a minor inconsistency with the value range 
of saturation and brightness, which according to the philips 
documentation is defined from 0...254.
I think currently in Phue it is handled from 0..255. That could somehow 
lead into inconsistencies when writing and reading back these values. I 
don't know, whether this is already handeled.

BR, André

**Comment by sqmk** [comment]
Can you create a new ticket for this, and provide PHP configuration/ini settings for both PHP 5.3 and PHP 5.6?

Thanks.

**Pull request merged**
